// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: proto/square.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SquareCaculator_SayHello_FullMethodName = "/proto.SquareCaculator/SayHello"
)

// SquareCaculatorClient is the client API for SquareCaculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquareCaculatorClient interface {
	SayHello(ctx context.Context, in *SquareRequest, opts ...grpc.CallOption) (*SquareReply, error)
}

type squareCaculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewSquareCaculatorClient(cc grpc.ClientConnInterface) SquareCaculatorClient {
	return &squareCaculatorClient{cc}
}

func (c *squareCaculatorClient) SayHello(ctx context.Context, in *SquareRequest, opts ...grpc.CallOption) (*SquareReply, error) {
	out := new(SquareReply)
	err := c.cc.Invoke(ctx, SquareCaculator_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquareCaculatorServer is the server API for SquareCaculator service.
// All implementations must embed UnimplementedSquareCaculatorServer
// for forward compatibility
type SquareCaculatorServer interface {
	SayHello(context.Context, *SquareRequest) (*SquareReply, error)
	mustEmbedUnimplementedSquareCaculatorServer()
}

// UnimplementedSquareCaculatorServer must be embedded to have forward compatible implementations.
type UnimplementedSquareCaculatorServer struct {
}

func (UnimplementedSquareCaculatorServer) SayHello(context.Context, *SquareRequest) (*SquareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSquareCaculatorServer) mustEmbedUnimplementedSquareCaculatorServer() {}

// UnsafeSquareCaculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquareCaculatorServer will
// result in compilation errors.
type UnsafeSquareCaculatorServer interface {
	mustEmbedUnimplementedSquareCaculatorServer()
}

func RegisterSquareCaculatorServer(s grpc.ServiceRegistrar, srv SquareCaculatorServer) {
	s.RegisterService(&SquareCaculator_ServiceDesc, srv)
}

func _SquareCaculator_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquareCaculatorServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquareCaculator_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquareCaculatorServer).SayHello(ctx, req.(*SquareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquareCaculator_ServiceDesc is the grpc.ServiceDesc for SquareCaculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquareCaculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SquareCaculator",
	HandlerType: (*SquareCaculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SquareCaculator_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/square.proto",
}
